import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Play, CheckCircle, Clock, XCircle, Loader2, RefreshCw, AlertCircle, PackageOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/status-badge";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Progress } from "@/components/ui/progress";
import { useWorkflow } from "@/hooks/use-workflows";
import { useWorkflowJobs, useJobStatus } from "@/hooks/use-jobs";
import { ContentResultCard } from "@/components/content/ContentResultCard";
import { api } from "@/lib/api";
import { toast } from "sonner";
import type { JobStatus } from "@/types/mcp";

const stepStatusIcons: Record<string, React.ReactNode> = {
  completed: <CheckCircle className="h-5 w-5 text-green-500" />,
  running: <Loader2 className="h-5 w-5 text-warning animate-spin" />,
  pending: <Clock className="h-5 w-5 text-muted-foreground" />,
  failed: <XCircle className="h-5 w-5 text-destructive" />,
};

function WorkflowDetailSkeleton() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Skeleton className="h-10 w-10" />
        <div className="flex-1">
          <Skeleton className="h-7 w-64 mb-2" />
          <Skeleton className="h-4 w-96" />
        </div>
        <Skeleton className="h-10 w-32" />
      </div>
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <Skeleton className="h-5 w-40" />
            </CardHeader>
            <CardContent className="grid gap-4 sm:grid-cols-3">
              <Skeleton className="h-12" />
              <Skeleton className="h-12" />
              <Skeleton className="h-12" />
            </CardContent>
          </Card>
        </div>
        <div>
          <Card>
            <CardHeader>
              <Skeleton className="h-5 w-24" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-20" />
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

export default function WorkflowDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { workflow, isLoading, error, runWorkflow, isRunning } = useWorkflow(id);
  const { jobs, refetch: refetchJobs } = useWorkflowJobs(id, 5);
  
  const [currentJobId, setCurrentJobId] = useState<string | null>(null);
  const [savingContentId, setSavingContentId] = useState<string | null>(null);
  const { job: pollingJob, isPolling, startPolling } = useJobStatus(currentJobId);

  // Get the most recent job for display
  const latestJob = pollingJob || jobs[0];

  // Fetch content generated by the completed job
  const { data: jobContent, isLoading: isLoadingContent } = useQuery({
    queryKey: ['content', 'job', latestJob?.id],
    queryFn: () => api.content.list({ job_id: latestJob!.id }),
    enabled: !!latestJob?.id && latestJob?.status === 'completed',
  });

  const handleRun = async () => {
    try {
      const response = await runWorkflow();
      setCurrentJobId(response.job_id);
      startPolling();
    } catch {
      // Error handled by hook
    }
  };

  const handleSaveToLibrary = async (contentId: string) => {
    setSavingContentId(contentId);
    try {
      await api.content.approve(contentId);
      toast.success("Content saved to library");
      // Refresh content list
      queryClient.invalidateQueries({ queryKey: ['content', 'job', latestJob?.id] });
    } catch (err) {
      toast.error("Failed to save content");
    } finally {
      setSavingContentId(null);
    }
  };

  // Refetch jobs and content when polling job completes
  useEffect(() => {
    if (pollingJob && (pollingJob.status === 'completed' || pollingJob.status === 'failed')) {
      refetchJobs();
      if (pollingJob.status === 'completed') {
        queryClient.invalidateQueries({ queryKey: ['content', 'job', pollingJob.id] });
      }
    }
  }, [pollingJob?.status, refetchJobs, queryClient, pollingJob?.id]);

  // Combine outputs from job and fetched content
  const generatedContent = jobContent || latestJob?.outputs || [];

  const getStepStatus = (stepIndex: number): JobStatus => {
    if (!latestJob) return 'pending';
    if (latestJob.status === 'completed') return 'completed';
    if (latestJob.status === 'failed') {
      const currentStep = latestJob.current_step ?? 0;
      return stepIndex < currentStep ? 'completed' : stepIndex === currentStep ? 'failed' : 'pending';
    }
    if (latestJob.status === 'running') {
      const currentStep = latestJob.current_step ?? 1;
      return stepIndex < currentStep - 1 ? 'completed' : stepIndex === currentStep - 1 ? 'running' : 'pending';
    }
    return 'pending';
  };

  if (isLoading) {
    return (
      <div className="animate-fade-in">
        <WorkflowDetailSkeleton />
      </div>
    );
  }

  if (error || !workflow) {
    return (
      <div className="space-y-6 animate-fade-in">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate('/workflows')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <h1 className="text-2xl font-bold text-foreground">Workflow Not Found</h1>
        </div>
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <AlertCircle className="h-12 w-12 text-destructive mb-4" />
            <p className="text-destructive mb-4">Failed to load workflow</p>
            <p className="text-sm text-muted-foreground mb-4">
              {error ? (error as Error).message : 'Workflow not found'}
            </p>
            <Button onClick={() => navigate('/workflows')} variant="outline">
              Back to Workflows
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Back Button & Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => navigate('/workflows')}>
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold text-foreground">{workflow.name}</h1>
          <p className="text-muted-foreground">{workflow.description}</p>
        </div>
        <Button 
          onClick={handleRun}
          disabled={isRunning || isPolling}
          className="gradient-primary text-primary-foreground"
        >
          {isRunning || isPolling ? (
            <span className="flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" />
              {isPolling ? 'Running...' : 'Starting...'}
            </span>
          ) : (
            <span className="flex items-center gap-2">
              <Play className="h-4 w-4" />
              Run Workflow
            </span>
          )}
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Workflow Info & Steps */}
        <div className="lg:col-span-2 space-y-6">
          {/* Info Card */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Workflow Information</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-4 sm:grid-cols-3">
              <div>
                <p className="text-sm text-muted-foreground">Target Platform</p>
                <p className="font-medium">{workflow.target_platform || workflow.targetPlatform || 'None'}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Total Steps</p>
                <p className="font-medium">{workflow.steps.length}</p>
              </div>
              <div>
                <p className="text-sm text-muted-foreground">Last Run</p>
                <p className="font-medium">
                  {workflow.last_run_at || workflow.lastRunAt
                    ? new Date(workflow.last_run_at || workflow.lastRunAt!).toLocaleString() 
                    : 'Never'}
                </p>
              </div>
            </CardContent>
          </Card>

          {/* Steps Card */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Workflow Steps</CardTitle>
              <CardDescription>Steps are executed in order by MCP</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {workflow.steps.map((step, index) => (
                  <div key={step.id || index} className="flex items-center gap-4">
                    <div className="flex-shrink-0 h-8 w-8 rounded-full bg-primary/10 flex items-center justify-center text-sm font-medium text-primary">
                      {step.order}
                    </div>
                    <div className="flex-1">
                      <p className="font-medium">{step.name || `Step ${step.order}`}</p>
                      <p className="text-sm text-muted-foreground">Tool: {step.tool_name || step.toolName}</p>
                    </div>
                    {stepStatusIcons[getStepStatus(index)]}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Logs Card */}
          {latestJob && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Execution Logs</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-muted rounded-lg p-4 font-mono text-sm max-h-64 overflow-y-auto">
                  {latestJob.logs ? (
                    Array.isArray(latestJob.logs) ? (
                      latestJob.logs.map((log, i) => (
                        <div key={i} className="text-muted-foreground hover:text-foreground">
                          {String(log)}
                        </div>
                      ))
                    ) : (
                      <div className="text-muted-foreground">
                        {JSON.stringify(latestJob.logs, null, 2)}
                      </div>
                    )
                  ) : (
                    <div className="text-muted-foreground">No logs available</div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Right Sidebar - Job Status & History */}
        <div className="space-y-6">
          {/* Current Job Status */}
          {latestJob && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Job Status</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Status</span>
                  <StatusBadge status={latestJob.status} />
                </div>
                
                {(latestJob.status === 'running' || latestJob.status === 'pending') && (
                  <div className="space-y-2">
                    <Progress value={latestJob.progress ?? 0} className="h-2" />
                    <p className="text-xs text-muted-foreground text-center">
                      {latestJob.progress ?? 0}% complete
                    </p>
                  </div>
                )}
                
                <Separator />
                <div className="space-y-2 text-sm">
                  {latestJob.started_at || latestJob.startedAt ? (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Started</span>
                      <span>{new Date(latestJob.started_at || latestJob.startedAt!).toLocaleTimeString()}</span>
                    </div>
                  ) : null}
                  {(latestJob.completed_at || latestJob.completedAt) && (
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Completed</span>
                      <span>{new Date(latestJob.completed_at || latestJob.completedAt!).toLocaleTimeString()}</span>
                    </div>
                  )}
                  {latestJob.error && (
                    <div className="p-2 bg-destructive/10 rounded text-destructive text-xs">
                      {latestJob.error}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Job History */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center justify-between">
                Recent Jobs
                <Button variant="ghost" size="sm" onClick={() => refetchJobs()}>
                  <RefreshCw className="h-4 w-4" />
                </Button>
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {jobs.length > 0 ? (
                jobs.slice(0, 5).map((job) => (
                  <div 
                    key={job.id}
                    className="flex items-center justify-between p-2 rounded-lg bg-muted/50"
                  >
                    <div className="text-sm">
                      <p className="font-mono text-xs text-muted-foreground">
                        {job.id.slice(0, 8)}...
                      </p>
                      <p className="text-xs text-muted-foreground">
                        {job.started_at || job.startedAt 
                          ? new Date(job.started_at || job.startedAt!).toLocaleString()
                          : 'Not started'}
                      </p>
                    </div>
                    <StatusBadge status={job.status} />
                  </div>
                ))
              ) : (
                <p className="text-sm text-muted-foreground text-center py-4">
                  No jobs yet
                </p>
              )}
            </CardContent>
          </Card>

          {/* Generated Content */}
          {latestJob?.status === 'completed' && (
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Generated Content</CardTitle>
                <CardDescription>Results from this workflow run</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {isLoadingContent ? (
                  <div className="space-y-3">
                    <Skeleton className="h-24" />
                    <Skeleton className="h-24" />
                  </div>
                ) : generatedContent.length > 0 ? (
                  <div className="space-y-3">
                    {generatedContent.map((content) => (
                      <ContentResultCard
                        key={content.id}
                        content={content}
                        onSaveToLibrary={handleSaveToLibrary}
                        isSaving={savingContentId === content.id}
                      />
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-6">
                    <PackageOpen className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
                    <p className="text-sm text-muted-foreground">No content generated yet</p>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
